# Generated by Django 2.0.4 on 2018-04-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import musiccreate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('album_type', models.CharField(max_length=50)),
                ('share', models.BooleanField(default=True)),
                ('album_cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=musiccreate.models.upload_image_location, width_field='height_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_uploaded', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('about', models.CharField(blank=True, max_length=300, null=True)),
                ('artist_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=musiccreate.models.upload_image_location, width_field='height_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('music_type', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('share', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to=musiccreate.models.upload_music_location)),
                ('duration_min', models.CharField(max_length=10)),
                ('duration_sec', models.CharField(max_length=3)),
                ('music_cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=musiccreate.models.upload_image_location, width_field='height_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='musiccreate.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musiccreate.Artist')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_musics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('playlist_type', models.CharField(max_length=50)),
                ('share', models.BooleanField(default=True)),
                ('playlist_cover', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=musiccreate.models.upload_image_location, width_field='height_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_set', to='musiccreate.Playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_musics', to='musiccreate.Music')),
            ],
        ),
    ]
